work_dir: work_dir/ntu60/xview/joint
# # work_dir: work_dir/ntu60/xview/joint_motion
# # work_dir: work_dir/ntu60/xview/bone
# work_dir: work_dir/ntu60/xview/bone_motion

num_epoch: 65
cuda: True
device: 0

# MODEL
model_args:
  model_name: fcsa_gcn.Model
  num_classes: 15
  input_channels: 3 
  residual: True
  dropout: 0.5
  num_person: 1
  graph: graph.ntu_rgb_d.Graph  
  num_nodes: 25

# OPTIMIZER
optimizer_args:
  optimizer: SGD
  base_lr: 0.1
  lr_step: [35,60,75]
  momentum: 0.9
  nesterov: True
  weight_decay: 0.0005
  warm_up_epoch: 5
  cosine_epoch: 60 #80


# TRAIN TEST FEEDER
feeder: feeders.feeder.Feeder
train_feeder_args:  
  data_path: Dataset/Ntu15_withPre/xview/train_data_joint.npy
  label_path: Dataset/Ntu15_withPre/xview/train_label.pkl
  normalization: False
  random_shift: False
  random_choose: False
  random_move: False 
  window_size: -1
  batch_size: 64
  num_worker: 0
  
  
test_feeder_args:
  data_path: Dataset/Ntu15_withPre/xview/val_data_joint.npy
  label_path: Dataset/Ntu15_withPre/xview/val_label.pkl
  normalization: False
  random_shift: False
  random_choose: False
  random_move: False 
  window_size: -1
  batch_size: 64
  num_worker: 0



